springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8083
spring:
  application.name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order_saga_group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  inventory:
    topic: inventory_topic
  payment:
    success-topic: payment_success_topic
    topic: payment_topic
  topic:
    payment-error: payment-error